### ISSUE TITLE
Songs will fail to analyse when the system language is set to Polish (and possibly other languages)

### ISSUE THREAD

**Issue by marysiamzawka** [thanik/rhythmaticc#1]
When you start analysing a file, it'll error saying that analysing failed after about 5 seconds.
Changing the system language to English (US) resolved the issue.

**Comment by thanik** [comment]
Can you provide a log file? It's in AppData\LocalLow\thanik\rhythmaticc.

**Comment by marysiamzawka** [comment]
[Player-prev.log](https://github.com/thanik/rhythmaticc/files/5092005/Player-prev.log)

**Comment by dexterw98** [comment]
I think the problem is with "," divider while in Polish region.

**Comment by thanik** [comment]
> I think the problem is with "," divider while in Polish region.

Yes, I'm currently fixing it so beta2 is incoming.

**Comment by thanik** [comment]
I just uploaded the second beta. Please let me know if it's working or not. Thank you.

**Comment by dexterw98** [comment]
It's working 👍 .

**Comment by thanik** [comment]
Thank you!
